language: go

python:
- "3.9.1"

addons:
  apt:
    packages:
    - "python3-pip"

services:
- docker

git:
  depth: 1

notifications:
  email: false

before_install:
- make prepare

script:
- make lint
